services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    hostname: dockge-vps
    container_name: dockge
    #    user: ${UID}:${GID}
    group_add:
      # getent group docker
      - ${DOCKER_GROUP}
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ${DOCKER_DIR}:${DOCKER_DIR}
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=${DOCKER_DIR}
      - PGID=${GID}
      - PUID=${UID}
networks: {}
